### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by o0oradaro0o** [picchipalarm/nanit-permission-scheduler#1]
Trying this in postman i just get:
```
{
    "message": "action not allowed"
}
```
back. my auth info works and all that. is there some trick i missed?

**Comment by picchipalarm** [comment]
I think nannit changed something with their Auth, I may have not updated the code or docs. I since started using nannits WiFi local only feature instead of this. However, if you still want to use this I'll go over the project soon

**Comment by o0oradaro0o** [comment]
Yo, it absolutely works I don't remember what i was doing wrong but your project was very helpful. 

I was really looking for a way to create a one button solution to turn off all notifications without turning off the camera, i was able to do that using the permissions endpoint you showcased but it also added restrictions to a user (turning off notification permissions also stops the user from having control over whether the camera is on or off)
if you happen to know how the heck to control the motion notifications and sound notifications over the API id be curious, I couldn't figure it out but i appreciate the start you gave me.

**Comment by picchipalarm** [comment]
Ok great!
The way I worked out the APIs was with using Charles proxy to read the traffic from the app. On android you can unpack and rebuild the apk adding a Charles proxy certificate, then you can read the traffic from the app on your pc. 
So if the app does what you want via an API call you could see how to use it.
